# Use the official gcc image
image: gcc

before_script:
    # Install build dependencies
    # We will install latest CMake
    - mkdir -p $HOME/.local
    - curl -s "https://cmake.org/files/v3.19/cmake-3.19.4-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C $HOME/.local
    - export PATH=$HOME/.local/bin:$PATH
    # install cmocka
    - wget http://git.cryptomilk.org/projects/cmocka.git/snapshot/master.tar.gz
    - tar -xvf master.tar.gz
    - cd master
    - mkdir build
    - cd build
    - cmake ..
    - make all install
    - cd ..
    - ldconfig
    # install adress sanitizer
    - apt-get install libasan5
    # install pyhon
    - apt-get install -y python-dev python-pip
    # install gcovr
    - pip install gcovr

myapp:
    # Build the application
    stage: build
    script:
        - rm -r build
        - mkdir build
        - cd build
        - cmake ..
        - make