variables:
  PROJECT_GROUP: gitlab-ci-intro-group/gitlabciimages
  FEDORA_BUILD: buildenv-fedora
  UBUNTU_BUILD: buildenv-ubuntu

stages:
  - build
  - test

fedora-build-job:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
  artifacts:
    expire_in: 1 week
    paths:
      - build

ubuntu-build-job:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$UBUNTU_BUILD
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
  artifacts:
    expire_in: 1 week
    paths:
      - build

fedora-test-job:
  stage: test
  script:
    - cd build
    - ./Driver/main
  dependencies:
    - fedora-build-job

ubuntu-test-job:
  stage: test
  script:
    - cd build
    - ./Driver/main
  dependencies:
    - ubuntu-build-job

